steps:
  # Docker イメージをビルドします
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/$_IMAGE_NAME:$COMMIT_SHA'
      - '--file'
      - 'Dockerimage' # Dockerfileの名前が 'Dockerimage' のため
      - '.'

  # ビルドしたイメージを Artifact Registry にプッシュします
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/$_IMAGE_NAME:$COMMIT_SHA'

# ビルドされたイメージの情報をCloud Buildのビルド履歴に保存します
images:
  - '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/$_IMAGE_NAME:$COMMIT_SHA'

# 置換可能な変数を定義します
substitutions:
  _LOCATION: asia-northeast1
  _AR_REPO: cloud-workstations-images
  _IMAGE_NAME: gossy-workstation
